-- 0001_core.sql — Ultra Link core schema
-- Design notes (see docs/ARCHITECTURE.md):
--  * One table `intents` for requests, offers and participations (side = seek | provide | join).
--  * intents/matches are LIST-partitioned by vertical (real estate, vehicles, ...). Every match query
--    is single-vertical, so partition pruning keeps hot indexes small. Matches are co-located with
--    their intents by vertical_id (same key would be the shard key in a distributed deployment).
--  * Matching never scans: points are found by range scans over a nested-set "place interval code"
--    (place_lft), and scopes are found by equality probes on intent_scopes with the point's ancestors.
--  * Only ACTIVE intents live in the matching indexes (partial indexes + scope rows deleted on close).
--  * Money = BIGINT minor units + currency + unit. Never floating point.

-- ───────────── reference data ─────────────
CREATE TABLE verticals (
  id      smallint PRIMARY KEY,
  code    text NOT NULL UNIQUE,
  name_ar text NOT NULL
);

CREATE TABLE deal_types (
  id       smallint PRIMARY KEY,
  code     text NOT NULL UNIQUE,
  name_ar  text NOT NULL,
  relation text NOT NULL CHECK (relation IN ('exchange', 'peer'))
);

CREATE TABLE categories (
  id             integer PRIMARY KEY,
  parent_id      integer REFERENCES categories (id),
  code           text NOT NULL UNIQUE CHECK (code ~ '^[a-z_]+(\.[a-z_]+)*$'),
  vertical_id    smallint NOT NULL REFERENCES verticals (id),
  name_ar        text NOT NULL,
  description_ar text NOT NULL,
  depth          smallint NOT NULL CHECK (depth >= 0),
  relation       text NOT NULL CHECK (relation IN ('exchange', 'peer')),
  allowed_deals  smallint[] NOT NULL CHECK (cardinality(allowed_deals) > 0),
  keywords       text[] NOT NULL DEFAULT '{}',
  status         text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'proposed', 'retired')),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX categories_parent_idx ON categories (parent_id);

CREATE TABLE places (
  id        integer PRIMARY KEY,
  parent_id integer REFERENCES places (id),
  code      text NOT NULL UNIQUE,
  name_ar   text NOT NULL,
  kind      text NOT NULL CHECK (kind IN ('world', 'country', 'region', 'city', 'district', 'neighborhood', 'virtual')),
  depth     smallint NOT NULL,
  lft       integer NOT NULL,   -- nested-set interval with gaps ("place interval code")
  rgt       integer NOT NULL,
  lat       numeric(9, 6),
  lng       numeric(9, 6),
  aliases   text[] NOT NULL DEFAULT '{}',
  CHECK (lft < rgt),
  UNIQUE (lft),
  UNIQUE (rgt)
);
CREATE INDEX places_interval_idx ON places (lft, rgt);

CREATE TABLE attribute_defs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer NOT NULL REFERENCES categories (id),
  key         text NOT NULL CHECK (key ~ '^[a-z][a-z0-9_]*$'),
  label_ar    text NOT NULL,
  value_type  text NOT NULL CHECK (value_type IN ('int', 'bool', 'enum', 'text')),
  unit        text,
  min_value   numeric,
  max_value   numeric,
  enum_values jsonb CHECK (enum_values IS NULL OR jsonb_typeof(enum_values) = 'array'),
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'proposed', 'retired')),
  UNIQUE (category_id, key),
  CHECK ((value_type = 'enum') = (enum_values IS NOT NULL))
);

-- ───────────── users & sessions ─────────────
CREATE TABLE users (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id     uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  display_name  text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 80),
  handle        text UNIQUE CHECK (handle ~ '^[a-z0-9_]{3,40}$'),
  realm         text NOT NULL DEFAULT 'real' CHECK (realm IN ('real', 'synthetic')),
  contact_phone text,           -- revealed to a counterpart only after mutual consent
  persona_ar    text,           -- description for synthetic demo personas
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
  token_hash   bytea PRIMARY KEY,                 -- sha256(random token); raw token only in the cookie
  user_id      bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_idx ON sessions (user_id);
CREATE INDEX sessions_expiry_idx ON sessions (expires_at);

-- ───────────── conversations ─────────────
CREATE TABLE conversations (
  id               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id        uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  user_id          bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  state            text NOT NULL DEFAULT 'collecting' CHECK (state IN ('collecting', 'asking', 'saved', 'cancelled')),
  draft            jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(draft) = 'object'),
  pending_question jsonb,
  intent_vertical_id smallint,
  intent_id        bigint,
  revision         integer NOT NULL DEFAULT 0,          -- optimistic concurrency for concurrent turns
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX conversations_user_open_idx ON conversations (user_id, updated_at DESC) WHERE state IN ('collecting', 'asking');

CREATE TABLE conversation_messages (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
  role            text NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  modality        text CHECK (modality IN ('voice', 'text')),
  text            text NOT NULL,
  client_turn_id  uuid,                                   -- idempotency key from the client
  meta            jsonb NOT NULL DEFAULT '{}',
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX conversation_messages_conv_idx ON conversation_messages (conversation_id, id);
CREATE UNIQUE INDEX conversation_messages_turn_uq ON conversation_messages (conversation_id, client_turn_id) WHERE client_turn_id IS NOT NULL;

CREATE TABLE extraction_runs (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES conversations (id) ON DELETE CASCADE,
  message_id      bigint REFERENCES conversation_messages (id) ON DELETE CASCADE,
  engine          text NOT NULL CHECK (engine IN ('rules', 'jev', 'jev-sim')),
  model           text,
  input_hash      bytea NOT NULL,          -- sha256 of normalized text (no raw text duplicated here)
  output          jsonb NOT NULL,
  validated       boolean NOT NULL,
  error           text,
  latency_ms      integer,
  input_tokens    integer,
  output_tokens   integer,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX extraction_runs_conv_idx ON extraction_runs (conversation_id);
CREATE INDEX extraction_runs_created_idx ON extraction_runs (created_at);

-- ───────────── intents (partitioned by vertical) ─────────────
CREATE SEQUENCE intents_id_seq AS bigint;

CREATE TABLE intents (
  id              bigint NOT NULL DEFAULT nextval('intents_id_seq'),
  vertical_id     smallint NOT NULL REFERENCES verticals (id),
  public_id       uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id         bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  realm           text NOT NULL CHECK (realm IN ('real', 'synthetic')),
  side            text NOT NULL CHECK (side IN ('seek', 'provide', 'join')),
  category_id     integer NOT NULL REFERENCES categories (id),
  deal_type_id    smallint NOT NULL REFERENCES deal_types (id),
  status          text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'fulfilled', 'closed', 'expired')),
  version         integer NOT NULL DEFAULT 1 CHECK (version > 0),
  title_ar        text NOT NULL,
  source_text     text,                                  -- owner-only
  conversation_id bigint REFERENCES conversations (id) ON DELETE SET NULL,
  -- location
  point_place_id  integer REFERENCES places (id),       -- where the item/person is
  point_lft       integer,                               -- denormalized places.lft for range scans
  scope_strength  text NOT NULL DEFAULT 'required' CHECK (scope_strength IN ('required', 'preferred')),
  scope_place_ids integer[] NOT NULL DEFAULT '{}',      -- where a counterpart is acceptable ({} = anywhere)
  -- money (minor units; comparable only with same currency AND unit)
  price_op        text CHECK (price_op IN ('eq', 'lte', 'gte', 'between', 'approx')),
  price_lo        bigint CHECK (price_lo IS NULL OR price_lo >= 0),
  price_hi        bigint CHECK (price_hi IS NULL OR price_hi >= 0),
  currency        char(3) CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
  price_unit      text CHECK (price_unit IN ('total', 'month', 'year', 'week', 'day', 'hour', 'session', 'person')),
  price_strength  text CHECK (price_strength IN ('required', 'preferred')),
  negotiable      boolean NOT NULL DEFAULT false,
  -- time
  when_range      tstzrange,
  when_strength   text CHECK (when_strength IN ('required', 'preferred')),
  when_label_ar   text,
  -- flexible, registry-validated attributes and constraints
  attrs           jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(attrs) = 'object'),
  constraints     jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(constraints) = 'array'),
  expires_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  closed_at       timestamptz,
  PRIMARY KEY (vertical_id, id),
  UNIQUE (vertical_id, public_id),
  CHECK (price_lo IS NULL OR price_hi IS NULL OR price_lo <= price_hi),
  CHECK ((price_lo IS NULL AND price_hi IS NULL) OR price_op IS NOT NULL),
  CHECK (point_place_id IS NULL OR point_lft IS NOT NULL)
) PARTITION BY LIST (vertical_id);

CREATE TABLE intents_real_estate PARTITION OF intents FOR VALUES IN (1);
CREATE TABLE intents_vehicles    PARTITION OF intents FOR VALUES IN (2);
CREATE TABLE intents_services    PARTITION OF intents FOR VALUES IN (3);
CREATE TABLE intents_education   PARTITION OF intents FOR VALUES IN (4);
CREATE TABLE intents_activities  PARTITION OF intents FOR VALUES IN (5);
CREATE TABLE intents_goods       PARTITION OF intents FOR VALUES IN (6);
CREATE TABLE intents_other       PARTITION OF intents DEFAULT;  -- new verticals land here until a migration adds a partition

-- Global lookup by public id (API uses public ids; ids never leak).
CREATE TABLE intent_refs (
  public_id   uuid PRIMARY KEY,
  vertical_id smallint NOT NULL,
  intent_id   bigint NOT NULL,
  user_id     bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (vertical_id, intent_id) REFERENCES intents (vertical_id, id) ON DELETE CASCADE
);

-- Forward lookup: "points inside my scope" → range scan on point_lft within a category set.
CREATE INDEX intents_point_idx ON intents (realm, side, deal_type_id, category_id, point_lft)
  INCLUDE (price_lo, currency, price_unit) WHERE status = 'active';
-- Owner tabs (requests / offers) with keyset pagination.
CREATE INDEX intents_owner_idx ON intents (user_id, side, created_at DESC, id DESC);
-- Expiry sweep touches only active rows.
CREATE INDEX intents_expiry_idx ON intents (expires_at) WHERE status = 'active' AND expires_at IS NOT NULL;
-- Peer activities overlapping in time.
CREATE INDEX intents_when_idx ON intents USING gist (category_id, when_range) WHERE status = 'active' AND side = 'join';
-- Attribute analytics / pushdown (registry-validated keys only).
CREATE INDEX intents_attrs_idx ON intents USING gin (attrs jsonb_path_ops) WHERE status = 'active';

-- Reverse lookup: "whose scope contains my point" → equality probes with my ancestors.
-- One row per (active intent × scope place). Deleted when the intent stops being active.
CREATE TABLE intent_scopes (
  vertical_id  smallint NOT NULL,
  intent_id    bigint NOT NULL,
  realm        text NOT NULL,
  side         text NOT NULL,
  deal_type_id smallint NOT NULL,
  category_id  integer NOT NULL,
  place_id     integer NOT NULL REFERENCES places (id),
  PRIMARY KEY (vertical_id, intent_id, place_id),
  FOREIGN KEY (vertical_id, intent_id) REFERENCES intents (vertical_id, id) ON DELETE CASCADE
);
CREATE INDEX intent_scopes_probe_idx ON intent_scopes (vertical_id, realm, side, deal_type_id, category_id, place_id) INCLUDE (intent_id);

-- ───────────── matching ─────────────
CREATE SEQUENCE matches_id_seq AS bigint;
CREATE SEQUENCE match_eval_seq AS bigint;

CREATE TABLE matches (
  id               bigint NOT NULL DEFAULT nextval('matches_id_seq'),
  public_id        uuid NOT NULL DEFAULT gen_random_uuid(),
  vertical_id      smallint NOT NULL,
  kind             text NOT NULL CHECK (kind IN ('exchange', 'peer')),
  a_intent_id      bigint NOT NULL,   -- exchange: the seeker; peer: the lower intent id
  b_intent_id      bigint NOT NULL,   -- exchange: the provider; peer: the higher intent id
  a_user_id        bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  b_user_id        bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  state            text NOT NULL CHECK (state IN ('confirmed', 'possible', 'invalidated')),
  score            integer NOT NULL CHECK (score BETWEEN 0 AND 10000),
  reasons          jsonb NOT NULL DEFAULT '[]',
  missing          jsonb NOT NULL DEFAULT '[]',
  a_version        integer NOT NULL,
  b_version        integer NOT NULL,
  eval_seq         bigint NOT NULL,   -- monotonically increasing; older evaluations can never overwrite newer
  invalid_reason_ar text,
  first_matched_at timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (vertical_id, id),
  UNIQUE (vertical_id, a_intent_id, b_intent_id),
  UNIQUE (vertical_id, public_id),
  CHECK (a_intent_id <> b_intent_id),
  CHECK (a_user_id <> b_user_id),
  FOREIGN KEY (vertical_id, a_intent_id) REFERENCES intents (vertical_id, id) ON DELETE CASCADE,
  FOREIGN KEY (vertical_id, b_intent_id) REFERENCES intents (vertical_id, id) ON DELETE CASCADE
) PARTITION BY LIST (vertical_id);

CREATE TABLE matches_real_estate PARTITION OF matches FOR VALUES IN (1);
CREATE TABLE matches_vehicles    PARTITION OF matches FOR VALUES IN (2);
CREATE TABLE matches_services    PARTITION OF matches FOR VALUES IN (3);
CREATE TABLE matches_education   PARTITION OF matches FOR VALUES IN (4);
CREATE TABLE matches_activities  PARTITION OF matches FOR VALUES IN (5);
CREATE TABLE matches_goods       PARTITION OF matches FOR VALUES IN (6);
CREATE TABLE matches_other       PARTITION OF matches DEFAULT;

CREATE TABLE match_refs (
  public_id   uuid PRIMARY KEY,
  vertical_id smallint NOT NULL,
  match_id    bigint NOT NULL,
  FOREIGN KEY (vertical_id, match_id) REFERENCES matches (vertical_id, id) ON DELETE CASCADE
);

-- Per-user match lists (both sides), ranked, keyset-paginated.
CREATE INDEX matches_a_user_idx ON matches (a_user_id, state, score DESC, id DESC);
CREATE INDEX matches_b_user_idx ON matches (b_user_id, state, score DESC, id DESC);
CREATE INDEX matches_a_intent_idx ON matches (a_intent_id, state, score DESC, id DESC);
CREATE INDEX matches_b_intent_idx ON matches (b_intent_id, state, score DESC, id DESC);

-- One row per evaluation of an intent version: totals + exclusion reasons (for "why not" transparency).
CREATE TABLE match_runs (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  vertical_id    smallint NOT NULL,
  intent_id      bigint NOT NULL,
  intent_version integer NOT NULL,
  eval_seq       bigint NOT NULL,
  candidates     integer NOT NULL,
  confirmed      integer NOT NULL,
  possible       integer NOT NULL,
  excluded       integer NOT NULL,
  exclusions     jsonb NOT NULL DEFAULT '[]',
  truncated      boolean NOT NULL DEFAULT false,
  duration_ms    integer,
  trigger        text NOT NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (vertical_id, intent_id, intent_version, eval_seq),
  FOREIGN KEY (vertical_id, intent_id) REFERENCES intents (vertical_id, id) ON DELETE CASCADE
);
CREATE INDEX match_runs_latest_idx ON match_runs (vertical_id, intent_id, id DESC);

-- ───────────── contact requests (consent-based) ─────────────
CREATE TABLE contact_requests (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id      uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  vertical_id    smallint NOT NULL,
  match_id       bigint NOT NULL,
  requester_id   bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  recipient_id   bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  status         text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled')),
  message_ar     text CHECK (message_ar IS NULL OR char_length(message_ar) <= 500),
  created_at     timestamptz NOT NULL DEFAULT now(),
  responded_at   timestamptz,
  UNIQUE (vertical_id, match_id, requester_id),
  CHECK (requester_id <> recipient_id),
  FOREIGN KEY (vertical_id, match_id) REFERENCES matches (vertical_id, id) ON DELETE CASCADE
);
CREATE INDEX contact_requests_recipient_idx ON contact_requests (recipient_id, status);

-- ───────────── notifications (private to recipient) ─────────────
CREATE TABLE notifications (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  public_id    uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  recipient_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  kind         text NOT NULL,
  title_ar     text NOT NULL,
  body_ar      text,
  payload      jsonb NOT NULL DEFAULT '{}',
  dedupe_key   text NOT NULL,         -- one notification per (recipient, event); duplicates are impossible
  created_at   timestamptz NOT NULL DEFAULT now(),
  read_at      timestamptz,
  UNIQUE (recipient_id, dedupe_key)
);
CREATE INDEX notifications_recipient_idx ON notifications (recipient_id, created_at DESC, id DESC);
CREATE INDEX notifications_unread_idx ON notifications (recipient_id) WHERE read_at IS NULL;

-- ───────────── background jobs (SKIP LOCKED queue with leases) ─────────────
CREATE TABLE jobs (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  kind         text NOT NULL,
  payload      jsonb NOT NULL DEFAULT '{}',
  dedupe_key   text,
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'running', 'done', 'failed', 'superseded')),
  priority     smallint NOT NULL DEFAULT 100,
  run_at       timestamptz NOT NULL DEFAULT now(),
  attempts     integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 5,
  locked_by    text,
  locked_until timestamptz,
  last_error   text,
  result       jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  started_at   timestamptz,
  finished_at  timestamptz
);
CREATE UNIQUE INDEX jobs_dedupe_uq ON jobs (dedupe_key) WHERE status IN ('pending', 'running') AND dedupe_key IS NOT NULL;
CREATE INDEX jobs_ready_idx ON jobs (priority, run_at, id) WHERE status = 'pending';
CREATE INDEX jobs_lease_idx ON jobs (locked_until) WHERE status = 'running';

CREATE TABLE worker_heartbeats (
  worker_id  text PRIMARY KEY,
  beat_at    timestamptz NOT NULL DEFAULT now(),
  info       jsonb NOT NULL DEFAULT '{}'
);

-- ───────────── self-improvement loop (agents propose, humans approve) ─────────────
CREATE TABLE unknown_terms (
  term_norm   text NOT NULL,
  category_id integer NOT NULL DEFAULT 0,   -- 0 = unknown category
  hits        bigint NOT NULL DEFAULT 1,
  example     text,                          -- short, owner-consented snippet only
  first_seen  timestamptz NOT NULL DEFAULT now(),
  last_seen   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (term_norm, category_id)
);

CREATE TABLE schema_proposals (
  id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  kind           text NOT NULL CHECK (kind IN ('category', 'attribute', 'lexicon', 'index', 'partition', 'migration')),
  title          text NOT NULL,
  rationale      text NOT NULL,
  evidence       jsonb NOT NULL DEFAULT '{}',
  proposal       jsonb NOT NULL DEFAULT '{}',
  migration_file text,
  status         text NOT NULL DEFAULT 'proposed' CHECK (status IN ('proposed', 'approved', 'rejected', 'applied')),
  proposed_by    text NOT NULL,
  dedupe_key     text NOT NULL UNIQUE,
  created_at     timestamptz NOT NULL DEFAULT now(),
  decided_at     timestamptz,
  decided_by     text
);
